Package: ros-tutorials
Version: 0.0.0
Section: misc
Priority: extra
Architecture: any
Depends: ${misc:Depends} python-empy, cmake, make,
         @(PackagePrefix)genmsg, @(PackagePrefix)genpy, @(PackagePrefix)gencpp, $(PackagePrefix)roscpp_core
Build-Depends: debhelper (>= 7), cmake, gcc, make, python, python-empy, python-setuptools, 
               @(PackagePrefix)catkin, @(PackagePrefix)genmsg, 
               @(PackagePrefix)genpy, @(PackagePrefix)gencpp,
Description:
Author: 
Maintainer: 
Homepage: 

Catkin-ProjectName: ros_tutorials
Catkin-CopyrightType: willowgarage
Catkin-Depends: catkin, std_msgs, ros_comm, roscpp_core, common_msgs
Catkin-DebRulesType: cmake
